# Generated by Django 5.1.3 on 2024-12-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_app", "0004_student_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=20)),
                ("universal", models.BooleanField(default=False)),
                (
                    "tag_given_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_given",
                        to="staff_app.student",
                    ),
                ),
                (
                    "tag_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_received",
                        to="staff_app.student",
                    ),
                ),
            ],
        ),
    ]
