# Generated by Django 5.1.2 on 2025-01-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0009_main_notifications_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_notifications',
            old_name='post_id',
            new_name='post_number',
        ),
    ]
