version: '3'

services:
  redis:
    image: "redis:alpine"  # Use the lightweight Redis image
    ports:
      - "6379:6379"        # Expose Redis on port 6379

  django:
    build:
      context: .           # The context should be the directory containing the Dockerfile
      dockerfile: Dockerfile  # Specify the Dockerfile explicitly (optional if it's named "Dockerfile")
    command: daphne -b 0.0.0.0 -p 8000 college_media.asgi:application
    volumes:
      - .:/app             # Mount the project directory to the container
    ports:
      - "8000:8000"        # Expose Django on port 8000
    depends_on:
      - redis              # Ensure Redis starts before Django
    environment:
      - REDIS_HOST=redis   # Point to the Redis service name (Docker DNS)

networks:
  default:
    driver: bridge
