# Generated by Django 5.1.2 on 2024-11-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0004_student_profile_image'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='staff_app.student'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='like',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='staff_app.student'),
        ),
    ]
