# Generated by Django 5.1.3 on 2024-12-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_app", "0008_remove_tagmessage_tag_remove_tagmessage_sender_and_more"),
        ("user_app", "0002_like_liked_by_alter_like_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=20)),
                ("universal", models.BooleanField(default=False)),
                (
                    "tag_given_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_given",
                        to="staff_app.student",
                    ),
                ),
                (
                    "tag_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_received",
                        to="staff_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="staff_app.student",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="user_app.tag",
                    ),
                ),
            ],
        ),
    ]
